name: Build and test

on:
    # Only on pushes to main or one of the release branches we build on push
    push:
        branches:
            - main
            - "[0-9].[0-9]+-branch"
        tags:
            - "*"
    # Build pull requests
    pull_request:

jobs:
    test:
        strategy:
            matrix:
                py:
                    - "3.8"
                    - "3.9"
                    - "3.10"
                    - "3.11"
                    - "3.12"
                    - "pypy-3.9"
                    - "pypy-3.10"
                os:
                    - "ubuntu-latest"
                    - "windows-latest"
                    - "macos-latest"
                include:
                  - py: "pypy-3.9"
                    toxenv: "pypy39"
                  - py: "pypy-3.10"
                    toxenv: "pypy310"
                exclude:
                    # Don't run all PyPy versions except latest on
                    # Windows/macOS. They are expensive to run.
                    - os: "windows-latest"
                      py: "pypy-3.9"
                    - os: "macos-latest"
                      py: "pypy-3.9"

        name: "Python: ${{ matrix.py }}-${{ matrix.architecture }} on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.py }}
            - run: pip install tox
            - name: Running tox with specific toxenv
              if: ${{ matrix.toxenv != '' }}
              env:
                TOXENV: ${{ matrix.toxenv }}
              run: tox
            - name: Running tox for current python version
              if: ${{ matrix.toxenv == '' }}
              run: tox -e py
    coverage:
        runs-on: ubuntu-latest
        name: Validate coverage
        steps:
            - uses: actions/checkout@v4
            - name: Setup python 3.8
              uses: actions/setup-python@v5
              with:
                  python-version: 3.8
                  architecture: x64

            - run: pip install tox
            - run: tox -e py38,coverage
    docs:
        runs-on: ubuntu-latest
        name: Build the documentation
        steps:
            - uses: actions/checkout@v4
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.8
                  architecture: x64
            - run: pip install tox
            - run: tox -e docs
    lint:
        runs-on: ubuntu-latest
        name: Lint the package
        steps:
            - uses: actions/checkout@v4
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.8
                  architecture: x64
            - run: pip install tox
            - run: tox -e lint
